### PR TITLE
Bug in go files generated ref #38

### LINKED ISSUE #38: Add a field for version information in get features msg.
**Is your feature request related to a problem? Please describe.**
When you are building a not regular release `vX.Y.Z` the `git HEAD` should be used as version information.

**Describe the solution you'd like**
A new fiels in the `Features` msg.

**Describe alternatives you've considered**
Just this.

### PR DESCRIPTION
**Pull request by stdevAlDen**
Fixes #38

Changes:
- just a mistake generating go files

Does this change need to mentioned in CHANGELOG.md?

No

### CODE REVIEW

**Comment by stdevAlDen** [comment]
> Fixes #38
> 
> Changes:
> 
> * just a mistake generating go files
> 
> Does this change need to mentioned in CHANGELOG.md?
> 
> No

@therealssj I made a mistake in the [previous pr](https://github.com/skycoin/hardware-wallet-protob/pull/39), making a push of the org branch witouht mergin can be enough as what I need is the commit hash in the repo to update vendors, but a review for merge can be ok too as it is very short.
This is breaking my  builds on https://travis-ci.com/skycoin/hardware-wallet-go/builds/108751638#L1059

**Comment by stdevAlDen** [comment]
> > Fixes #38
> > Changes:
> > 
> > * just a mistake generating go files
> > 
> > Does this change need to mentioned in CHANGELOG.md?
> > No
> 
> @therealssj I made a mistake in the [previous pr](https://github.com/skycoin/hardware-wallet-protob/pull/39), making a push of the org branch witouht mergin can be enough as what I need is the commit hash in the repo to update vendors, but a review for merge can be ok too as it is very short.
> This is breaking my builds on https://travis-ci.com/skycoin/hardware-wallet-go/builds/108751638#L1059

this is the relevant change
relevant_change

**Comment by therealssj** [comment]
Does the makefile generate incorrect import path?

**Comment by stdevAlDen** [comment]
> Does the makefile generate incorrect import path?

@therealssj I'm not sure how this happend as we are patching this https://github.com/skycoin/hardware-wallet-protob/blob/master/Makefile#L103
But this was the mistake

**Comment by stdevAlDen** [comment]
> > Does the makefile generate incorrect import path?
> 
> @therealssj I'm not sure how this happend as we are patching this https://github.com/skycoin/hardware-wallet-protob/blob/master/Makefile#L103
> But this was the mistake

maybe an existing $(OUT_GO)/google/protobuf/descriptor.pb.go made the rule ignored.

**Comment by stdevAlDen** [comment]
> Does the makefile generate incorrect import path?
> Just wondering why the import path was incorrect in previous pr

@therealssj https://github.com/skycoin/hardware-wallet-protob/pull/40#issuecomment-484279929

**Comment by therealssj** [comment]
Did u manually fix it right now ?

**Comment by stdevAlDen** [comment]
> Did u manually fix it right now ?

@therealssj no manually, a `make clean-go` by a `make build-go` fixed it.

**Comment by stdevAlDen** [comment]
> > Did u manually fix it right now ?
> 
> @therealssj no with plumbing commands, a `make clean-go` by a `make build-go` fixed it.

@therealssj thank you :)

**Pull request merged**
